# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiGenbank.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clusterArch(object):
    def setupUi(self, clusterArch):
        clusterArch.setObjectName("clusterArch")
        clusterArch.resize(764, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(clusterArch.sizePolicy().hasHeightForWidth())
        clusterArch.setSizePolicy(sizePolicy)
        clusterArch.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(clusterArch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.prepareDatabase = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prepareDatabase.sizePolicy().hasHeightForWidth())
        self.prepareDatabase.setSizePolicy(sizePolicy)
        self.prepareDatabase.setObjectName("prepareDatabase")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.prepareDatabase)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.prepareDatabase)
        self.toolBox.setObjectName("toolBox")
        self.ncbiDL = QtWidgets.QWidget()
        self.ncbiDL.setGeometry(QtCore.QRect(0, 0, 710, 394))
        self.ncbiDL.setObjectName("ncbiDL")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ncbiDL)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.ncbiKeyword = QtWidgets.QLineEdit(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncbiKeyword.sizePolicy().hasHeightForWidth())
        self.ncbiKeyword.setSizePolicy(sizePolicy)
        self.ncbiKeyword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ncbiKeyword.setObjectName("ncbiKeyword")
        self.horizontalLayout_14.addWidget(self.ncbiKeyword)
        self.label_7 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.ncbiOrganism = QtWidgets.QLineEdit(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncbiOrganism.sizePolicy().hasHeightForWidth())
        self.ncbiOrganism.setSizePolicy(sizePolicy)
        self.ncbiOrganism.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ncbiOrganism.setObjectName("ncbiOrganism")
        self.horizontalLayout_14.addWidget(self.ncbiOrganism)
        self.label_8 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.ncbiAccession = QtWidgets.QLineEdit(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncbiAccession.sizePolicy().hasHeightForWidth())
        self.ncbiAccession.setSizePolicy(sizePolicy)
        self.ncbiAccession.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ncbiAccession.setObjectName("ncbiAccession")
        self.horizontalLayout_14.addWidget(self.ncbiAccession)
        self.searchNcbiBtn = QtWidgets.QPushButton(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchNcbiBtn.sizePolicy().hasHeightForWidth())
        self.searchNcbiBtn.setSizePolicy(sizePolicy)
        self.searchNcbiBtn.setObjectName("searchNcbiBtn")
        self.horizontalLayout_14.addWidget(self.searchNcbiBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_15 = QtWidgets.QLabel(self.ncbiDL)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_22.addWidget(self.label_15)
        self.minLength = QtWidgets.QLineEdit(self.ncbiDL)
        self.minLength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.minLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minLength.setObjectName("minLength")
        self.horizontalLayout_22.addWidget(self.minLength)
        self.label_17 = QtWidgets.QLabel(self.ncbiDL)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        self.maxLength = QtWidgets.QLineEdit(self.ncbiDL)
        self.maxLength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.maxLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxLength.setObjectName("maxLength")
        self.horizontalLayout_22.addWidget(self.maxLength)
        self.label_18 = QtWidgets.QLabel(self.ncbiDL)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_22.addWidget(self.label_18)
        self.numEntries = QtWidgets.QLineEdit(self.ncbiDL)
        self.numEntries.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.numEntries.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numEntries.setPlaceholderText("")
        self.numEntries.setObjectName("numEntries")
        self.horizontalLayout_22.addWidget(self.numEntries)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.line_7 = QtWidgets.QFrame(self.ncbiDL)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_10.addWidget(self.line_7)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_9 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_24.addWidget(self.label_9, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.line_8 = QtWidgets.QFrame(self.ncbiDL)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_10.addWidget(self.line_8)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ncbiFileSearchResults = QtWidgets.QListWidget(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncbiFileSearchResults.sizePolicy().hasHeightForWidth())
        self.ncbiFileSearchResults.setSizePolicy(sizePolicy)
        self.ncbiFileSearchResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ncbiFileSearchResults.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ncbiFileSearchResults.setObjectName("ncbiFileSearchResults")
        self.horizontalLayout_15.addWidget(self.ncbiFileSearchResults)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.ncbiDL)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20)
        self.searchFilter = QtWidgets.QLineEdit(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchFilter.sizePolicy().hasHeightForWidth())
        self.searchFilter.setSizePolicy(sizePolicy)
        self.searchFilter.setMaximumSize(QtCore.QSize(16777178, 16777215))
        self.searchFilter.setObjectName("searchFilter")
        self.verticalLayout_13.addWidget(self.searchFilter)
        self.clearSearchSelectionBtn = QtWidgets.QPushButton(self.ncbiDL)
        self.clearSearchSelectionBtn.setObjectName("clearSearchSelectionBtn")
        self.verticalLayout_13.addWidget(self.clearSearchSelectionBtn)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_19 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_26.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.totalSearchResults = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalSearchResults.sizePolicy().hasHeightForWidth())
        self.totalSearchResults.setSizePolicy(sizePolicy)
        self.totalSearchResults.setMinimumSize(QtCore.QSize(31, 0))
        self.totalSearchResults.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.totalSearchResults.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.totalSearchResults.setMidLineWidth(9)
        self.totalSearchResults.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalSearchResults.setObjectName("totalSearchResults")
        self.horizontalLayout_26.addWidget(self.totalSearchResults, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.addNcbiFilesBtn = QtWidgets.QPushButton(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNcbiFilesBtn.sizePolicy().hasHeightForWidth())
        self.addNcbiFilesBtn.setSizePolicy(sizePolicy)
        self.addNcbiFilesBtn.setObjectName("addNcbiFilesBtn")
        self.verticalLayout_13.addWidget(self.addNcbiFilesBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_10 = QtWidgets.QLabel(self.ncbiDL)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_25.addWidget(self.label_10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.line_9 = QtWidgets.QFrame(self.ncbiDL)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_10.addWidget(self.line_9)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(20)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ncbiFileDLlist = QtWidgets.QListWidget(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncbiFileDLlist.sizePolicy().hasHeightForWidth())
        self.ncbiFileDLlist.setSizePolicy(sizePolicy)
        self.ncbiFileDLlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ncbiFileDLlist.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ncbiFileDLlist.setObjectName("ncbiFileDLlist")
        self.horizontalLayout_17.addWidget(self.ncbiFileDLlist)
        self.removeNcbiFilesBtn = QtWidgets.QPushButton(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeNcbiFilesBtn.sizePolicy().hasHeightForWidth())
        self.removeNcbiFilesBtn.setSizePolicy(sizePolicy)
        self.removeNcbiFilesBtn.setObjectName("removeNcbiFilesBtn")
        self.horizontalLayout_17.addWidget(self.removeNcbiFilesBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.ncbiDL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.ncbiDLtotalFilesCt = QtWidgets.QLabel(self.ncbiDL)
        self.ncbiDLtotalFilesCt.setObjectName("ncbiDLtotalFilesCt")
        self.horizontalLayout_16.addWidget(self.ncbiDLtotalFilesCt)
        self.line_11 = QtWidgets.QFrame(self.ncbiDL)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_16.addWidget(self.line_11)
        self.label_13 = QtWidgets.QLabel(self.ncbiDL)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.ncbiFileDlDir = QtWidgets.QLineEdit(self.ncbiDL)
        self.ncbiFileDlDir.setReadOnly(True)
        self.ncbiFileDlDir.setObjectName("ncbiFileDlDir")
        self.horizontalLayout_16.addWidget(self.ncbiFileDlDir)
        self.selectNcbiFileDirBtn = QtWidgets.QPushButton(self.ncbiDL)
        self.selectNcbiFileDirBtn.setObjectName("selectNcbiFileDirBtn")
        self.horizontalLayout_16.addWidget(self.selectNcbiFileDirBtn)
        self.dlNcbiFilesBtn = QtWidgets.QPushButton(self.ncbiDL)
        self.dlNcbiFilesBtn.setObjectName("dlNcbiFilesBtn")
        self.horizontalLayout_16.addWidget(self.dlNcbiFilesBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.toolBox.addItem(self.ncbiDL, "")
        self.ncbiDiv = QtWidgets.QWidget()
        self.ncbiDiv.setGeometry(QtCore.QRect(0, 0, 710, 394))
        self.ncbiDiv.setObjectName("ncbiDiv")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ncbiDiv)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.priChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.priChk.setObjectName("priChk")
        self.gridLayout.addWidget(self.priChk, 0, 1, 1, 1)
        self.vrtChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.vrtChk.setObjectName("vrtChk")
        self.gridLayout.addWidget(self.vrtChk, 6, 1, 1, 1)
        self.stsChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.stsChk.setObjectName("stsChk")
        self.gridLayout.addWidget(self.stsChk, 2, 1, 1, 1)
        self.patChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.patChk.setObjectName("patChk")
        self.gridLayout.addWidget(self.patChk, 6, 0, 1, 1)
        self.envChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.envChk.setObjectName("envChk")
        self.gridLayout.addWidget(self.envChk, 1, 0, 1, 1)
        self.invChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.invChk.setObjectName("invChk")
        self.gridLayout.addWidget(self.invChk, 4, 0, 1, 1)
        self.htgChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.htgChk.setObjectName("htgChk")
        self.gridLayout.addWidget(self.htgChk, 3, 0, 1, 1)
        self.rodChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.rodChk.setObjectName("rodChk")
        self.gridLayout.addWidget(self.rodChk, 1, 1, 1, 1)
        self.vrlChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.vrlChk.setObjectName("vrlChk")
        self.gridLayout.addWidget(self.vrlChk, 5, 1, 1, 1)
        self.synChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.synChk.setObjectName("synChk")
        self.gridLayout.addWidget(self.synChk, 3, 1, 1, 1)
        self.gssChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.gssChk.setObjectName("gssChk")
        self.gridLayout.addWidget(self.gssChk, 2, 0, 1, 1)
        self.plnChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.plnChk.setObjectName("plnChk")
        self.gridLayout.addWidget(self.plnChk, 7, 0, 1, 1)
        self.mamChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.mamChk.setObjectName("mamChk")
        self.gridLayout.addWidget(self.mamChk, 5, 0, 1, 1)
        self.tsaChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.tsaChk.setObjectName("tsaChk")
        self.gridLayout.addWidget(self.tsaChk, 4, 1, 1, 1)
        self.bctChk = QtWidgets.QCheckBox(self.ncbiDiv)
        self.bctChk.setObjectName("bctChk")
        self.gridLayout.addWidget(self.bctChk, 0, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.ncbiDiv)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.totalFilesGbDiv = QtWidgets.QLabel(self.ncbiDiv)
        self.totalFilesGbDiv.setObjectName("totalFilesGbDiv")
        self.horizontalLayout_19.addWidget(self.totalFilesGbDiv)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.ncbiDiv)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.estSize = QtWidgets.QLabel(self.ncbiDiv)
        self.estSize.setObjectName("estSize")
        self.horizontalLayout_20.addWidget(self.estSize)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.checkRequestBtn = QtWidgets.QPushButton(self.ncbiDiv)
        self.checkRequestBtn.setObjectName("checkRequestBtn")
        self.verticalLayout_11.addWidget(self.checkRequestBtn)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.line_10 = QtWidgets.QFrame(self.ncbiDiv)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_12.addWidget(self.line_10)
        self.label_12 = QtWidgets.QLabel(self.ncbiDiv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.gbDivDLoutputDir = QtWidgets.QLineEdit(self.ncbiDiv)
        self.gbDivDLoutputDir.setReadOnly(True)
        self.gbDivDLoutputDir.setObjectName("gbDivDLoutputDir")
        self.horizontalLayout_21.addWidget(self.gbDivDLoutputDir)
        self.selectGbDivDirBtn = QtWidgets.QPushButton(self.ncbiDiv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectGbDivDirBtn.sizePolicy().hasHeightForWidth())
        self.selectGbDivDirBtn.setSizePolicy(sizePolicy)
        self.selectGbDivDirBtn.setObjectName("selectGbDivDirBtn")
        self.horizontalLayout_21.addWidget(self.selectGbDivDirBtn)
        self.downloadGbDivFileBtn = QtWidgets.QPushButton(self.ncbiDiv)
        self.downloadGbDivFileBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadGbDivFileBtn.sizePolicy().hasHeightForWidth())
        self.downloadGbDivFileBtn.setSizePolicy(sizePolicy)
        self.downloadGbDivFileBtn.setObjectName("downloadGbDivFileBtn")
        self.horizontalLayout_21.addWidget(self.downloadGbDivFileBtn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.toolBox.addItem(self.ncbiDiv, "")
        self.filesDB = QtWidgets.QWidget()
        self.filesDB.setGeometry(QtCore.QRect(0, 0, 710, 394))
        self.filesDB.setObjectName("filesDB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filesDB)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gbkPathLabel = QtWidgets.QLabel(self.filesDB)
        self.gbkPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.gbkPathLabel.setObjectName("gbkPathLabel")
        self.horizontalLayout_3.addWidget(self.gbkPathLabel)
        self.genbankDirPath = QtWidgets.QLineEdit(self.filesDB)
        self.genbankDirPath.setReadOnly(True)
        self.genbankDirPath.setClearButtonEnabled(True)
        self.genbankDirPath.setObjectName("genbankDirPath")
        self.horizontalLayout_3.addWidget(self.genbankDirPath)
        self.genbankDirBtn = QtWidgets.QPushButton(self.filesDB)
        self.genbankDirBtn.setObjectName("genbankDirBtn")
        self.horizontalLayout_3.addWidget(self.genbankDirBtn)
        self.addGenbankBtn = QtWidgets.QPushButton(self.filesDB)
        self.addGenbankBtn.setObjectName("addGenbankBtn")
        self.horizontalLayout_3.addWidget(self.addGenbankBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.genbankList = QtWidgets.QListWidget(self.filesDB)
        self.genbankList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genbankList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.genbankList.setObjectName("genbankList")
        self.verticalLayout.addWidget(self.genbankList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.filesDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.totalFiles = QtWidgets.QLabel(self.filesDB)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalFiles.setFont(font)
        self.totalFiles.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.totalFiles.setObjectName("totalFiles")
        self.horizontalLayout_6.addWidget(self.totalFiles)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DatabasePathLabel = QtWidgets.QLabel(self.filesDB)
        self.DatabasePathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.DatabasePathLabel.setObjectName("DatabasePathLabel")
        self.horizontalLayout_4.addWidget(self.DatabasePathLabel)
        self.dbOutputDir = QtWidgets.QLineEdit(self.filesDB)
        self.dbOutputDir.setReadOnly(True)
        self.dbOutputDir.setClearButtonEnabled(True)
        self.dbOutputDir.setObjectName("dbOutputDir")
        self.horizontalLayout_4.addWidget(self.dbOutputDir)
        self.chooseDBoutputDirBtn = QtWidgets.QPushButton(self.filesDB)
        self.chooseDBoutputDirBtn.setObjectName("chooseDBoutputDirBtn")
        self.horizontalLayout_4.addWidget(self.chooseDBoutputDirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deleteGenbankBtn = QtWidgets.QPushButton(self.filesDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteGenbankBtn.sizePolicy().hasHeightForWidth())
        self.deleteGenbankBtn.setSizePolicy(sizePolicy)
        self.deleteGenbankBtn.setObjectName("deleteGenbankBtn")
        self.horizontalLayout_2.addWidget(self.deleteGenbankBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.createDbBtn = QtWidgets.QPushButton(self.filesDB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDbBtn.sizePolicy().hasHeightForWidth())
        self.createDbBtn.setSizePolicy(sizePolicy)
        self.createDbBtn.setObjectName("createDbBtn")
        self.horizontalLayout_2.addWidget(self.createDbBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.genbankList.raise_()
        self.toolBox.addItem(self.filesDB, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.tabWidget.addTab(self.prepareDatabase, "")
        self.searchtab = QtWidgets.QWidget()
        self.searchtab.setObjectName("searchtab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.searchtab)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.GeneFilePath = QtWidgets.QLineEdit(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneFilePath.sizePolicy().hasHeightForWidth())
        self.GeneFilePath.setSizePolicy(sizePolicy)
        self.GeneFilePath.setReadOnly(True)
        self.GeneFilePath.setObjectName("GeneFilePath")
        self.horizontalLayout_8.addWidget(self.GeneFilePath)
        self.addGenefilePathBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefilePathBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGenefilePathBtn.sizePolicy().hasHeightForWidth())
        self.addGenefilePathBtn.setSizePolicy(sizePolicy)
        self.addGenefilePathBtn.setObjectName("addGenefilePathBtn")
        self.horizontalLayout_8.addWidget(self.addGenefilePathBtn)
        self.addGenefileBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefileBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGenefileBtn.sizePolicy().hasHeightForWidth())
        self.addGenefileBtn.setSizePolicy(sizePolicy)
        self.addGenefileBtn.setObjectName("addGenefileBtn")
        self.horizontalLayout_8.addWidget(self.addGenefileBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.geneList = QtWidgets.QListWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geneList.sizePolicy().hasHeightForWidth())
        self.geneList.setSizePolicy(sizePolicy)
        self.geneList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.geneList.setObjectName("geneList")
        self.horizontalLayout_10.addWidget(self.geneList)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.addGeneSeqBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGeneSeqBtn.sizePolicy().hasHeightForWidth())
        self.addGeneSeqBtn.setSizePolicy(sizePolicy)
        self.addGeneSeqBtn.setObjectName("addGeneSeqBtn")
        self.verticalLayout_7.addWidget(self.addGeneSeqBtn)
        self.addGeneBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGeneBtn.sizePolicy().hasHeightForWidth())
        self.addGeneBtn.setSizePolicy(sizePolicy)
        self.addGeneBtn.setObjectName("addGeneBtn")
        self.verticalLayout_7.addWidget(self.addGeneBtn)
        self.clearGeneBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearGeneBtn.sizePolicy().hasHeightForWidth())
        self.clearGeneBtn.setSizePolicy(sizePolicy)
        self.clearGeneBtn.setObjectName("clearGeneBtn")
        self.verticalLayout_7.addWidget(self.clearGeneBtn)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.line_2 = QtWidgets.QFrame(self.searchtab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.hmmFilePath = QtWidgets.QLineEdit(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmmFilePath.sizePolicy().hasHeightForWidth())
        self.hmmFilePath.setSizePolicy(sizePolicy)
        self.hmmFilePath.setObjectName("hmmFilePath")
        self.horizontalLayout_11.addWidget(self.hmmFilePath)
        self.addHMMfilePathBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMfilePathBtn.sizePolicy().hasHeightForWidth())
        self.addHMMfilePathBtn.setSizePolicy(sizePolicy)
        self.addHMMfilePathBtn.setObjectName("addHMMfilePathBtn")
        self.horizontalLayout_11.addWidget(self.addHMMfilePathBtn)
        self.addHMMfilebtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMfilebtn.sizePolicy().hasHeightForWidth())
        self.addHMMfilebtn.setSizePolicy(sizePolicy)
        self.addHMMfilebtn.setObjectName("addHMMfilebtn")
        self.horizontalLayout_11.addWidget(self.addHMMfilebtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.hmmList = QtWidgets.QListWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmmList.sizePolicy().hasHeightForWidth())
        self.hmmList.setSizePolicy(sizePolicy)
        self.hmmList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.hmmList.setObjectName("hmmList")
        self.horizontalLayout_12.addWidget(self.hmmList)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.addHMMbtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMbtn.sizePolicy().hasHeightForWidth())
        self.addHMMbtn.setSizePolicy(sizePolicy)
        self.addHMMbtn.setObjectName("addHMMbtn")
        self.verticalLayout_8.addWidget(self.addHMMbtn)
        self.clearHMMbtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearHMMbtn.sizePolicy().hasHeightForWidth())
        self.clearHMMbtn.setSizePolicy(sizePolicy)
        self.clearHMMbtn.setObjectName("clearHMMbtn")
        self.verticalLayout_8.addWidget(self.clearHMMbtn)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_12.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.line_6 = QtWidgets.QFrame(self.searchtab)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_13.addWidget(self.line_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.databaseLabel = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel.setObjectName("databaseLabel")
        self.horizontalLayout.addWidget(self.databaseLabel)
        self.dataBaseSelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataBaseSelector.sizePolicy().hasHeightForWidth())
        self.dataBaseSelector.setSizePolicy(sizePolicy)
        self.dataBaseSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.dataBaseSelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.dataBaseSelector.setObjectName("dataBaseSelector")
        self.dataBaseSelector.addItem("")
        self.horizontalLayout.addWidget(self.dataBaseSelector)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.searchtab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.searchtab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.searchList = QtWidgets.QTableWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchList.sizePolicy().hasHeightForWidth())
        self.searchList.setSizePolicy(sizePolicy)
        self.searchList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.searchList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchList.setColumnCount(3)
        self.searchList.setObjectName("searchList")
        self.searchList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(2, item)
        self.searchList.horizontalHeader().setCascadingSectionResizes(True)
        self.searchList.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.searchList)
        self.removeSearchTermBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeSearchTermBtn.sizePolicy().hasHeightForWidth())
        self.removeSearchTermBtn.setSizePolicy(sizePolicy)
        self.removeSearchTermBtn.setObjectName("removeSearchTermBtn")
        self.verticalLayout_3.addWidget(self.removeSearchTermBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.searchtab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.searchtab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self.searchtab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.hitsNeededSpinBox = QtWidgets.QSpinBox(self.searchtab)
        self.hitsNeededSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hitsNeededSpinBox.sizePolicy().hasHeightForWidth())
        self.hitsNeededSpinBox.setSizePolicy(sizePolicy)
        self.hitsNeededSpinBox.setObjectName("hitsNeededSpinBox")
        self.horizontalLayout_7.addWidget(self.hitsNeededSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.searchtab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.databaseLabel_2 = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.horizontalLayout_9.addWidget(self.databaseLabel_2)
        self.outputDirectorySelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectorySelector.sizePolicy().hasHeightForWidth())
        self.outputDirectorySelector.setSizePolicy(sizePolicy)
        self.outputDirectorySelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.outputDirectorySelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.outputDirectorySelector.setObjectName("outputDirectorySelector")
        self.outputDirectorySelector.addItem("")
        self.horizontalLayout_9.addWidget(self.outputDirectorySelector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setParamsBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setParamsBtn.sizePolicy().hasHeightForWidth())
        self.setParamsBtn.setSizePolicy(sizePolicy)
        self.setParamsBtn.setObjectName("setParamsBtn")
        self.horizontalLayout_5.addWidget(self.setParamsBtn)
        self.runSearch = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runSearch.sizePolicy().hasHeightForWidth())
        self.runSearch.setSizePolicy(sizePolicy)
        self.runSearch.setObjectName("runSearch")
        self.horizontalLayout_5.addWidget(self.runSearch, 0, QtCore.Qt.AlignLeft)
        self.closeBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_5.addWidget(self.closeBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.searchtab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        clusterArch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clusterArch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        clusterArch.setMenuBar(self.menubar)
        self.actionSet_Database = QtWidgets.QAction(clusterArch)
        self.actionSet_Database.setObjectName("actionSet_Database")
        self.actionOpen_Gene_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_Gene_File.setObjectName("actionOpen_Gene_File")
        self.actionOpen_HMM_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_HMM_File.setObjectName("actionOpen_HMM_File")
        self.menuFile.addAction(self.actionSet_Database)
        self.menuFile.addAction(self.actionOpen_Gene_File)
        self.menuFile.addAction(self.actionOpen_HMM_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(clusterArch)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(5)
        self.dataBaseSelector.setCurrentIndex(-1)
        self.outputDirectorySelector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(clusterArch)
        clusterArch.setTabOrder(self.genbankDirBtn, self.genbankDirPath)
        clusterArch.setTabOrder(self.genbankDirPath, self.addGenbankBtn)
        clusterArch.setTabOrder(self.addGenbankBtn, self.tabWidget)
        clusterArch.setTabOrder(self.tabWidget, self.genbankList)
        clusterArch.setTabOrder(self.genbankList, self.dbOutputDir)
        clusterArch.setTabOrder(self.dbOutputDir, self.chooseDBoutputDirBtn)
        clusterArch.setTabOrder(self.chooseDBoutputDirBtn, self.deleteGenbankBtn)
        clusterArch.setTabOrder(self.deleteGenbankBtn, self.createDbBtn)
        clusterArch.setTabOrder(self.createDbBtn, self.GeneFilePath)
        clusterArch.setTabOrder(self.GeneFilePath, self.addGenefilePathBtn)
        clusterArch.setTabOrder(self.addGenefilePathBtn, self.addGenefileBtn)
        clusterArch.setTabOrder(self.addGenefileBtn, self.geneList)
        clusterArch.setTabOrder(self.geneList, self.addGeneSeqBtn)
        clusterArch.setTabOrder(self.addGeneSeqBtn, self.addGeneBtn)
        clusterArch.setTabOrder(self.addGeneBtn, self.clearGeneBtn)
        clusterArch.setTabOrder(self.clearGeneBtn, self.hmmFilePath)
        clusterArch.setTabOrder(self.hmmFilePath, self.addHMMfilePathBtn)
        clusterArch.setTabOrder(self.addHMMfilePathBtn, self.addHMMfilebtn)
        clusterArch.setTabOrder(self.addHMMfilebtn, self.hmmList)
        clusterArch.setTabOrder(self.hmmList, self.addHMMbtn)
        clusterArch.setTabOrder(self.addHMMbtn, self.clearHMMbtn)
        clusterArch.setTabOrder(self.clearHMMbtn, self.dataBaseSelector)
        clusterArch.setTabOrder(self.dataBaseSelector, self.searchList)
        clusterArch.setTabOrder(self.searchList, self.removeSearchTermBtn)
        clusterArch.setTabOrder(self.removeSearchTermBtn, self.hitsNeededSpinBox)
        clusterArch.setTabOrder(self.hitsNeededSpinBox, self.outputDirectorySelector)
        clusterArch.setTabOrder(self.outputDirectorySelector, self.setParamsBtn)
        clusterArch.setTabOrder(self.setParamsBtn, self.runSearch)
        clusterArch.setTabOrder(self.runSearch, self.closeBtn)
        clusterArch.setTabOrder(self.closeBtn, self.ncbiKeyword)
        clusterArch.setTabOrder(self.ncbiKeyword, self.ncbiOrganism)
        clusterArch.setTabOrder(self.ncbiOrganism, self.ncbiAccession)
        clusterArch.setTabOrder(self.ncbiAccession, self.searchNcbiBtn)
        clusterArch.setTabOrder(self.searchNcbiBtn, self.ncbiFileSearchResults)
        clusterArch.setTabOrder(self.ncbiFileSearchResults, self.addNcbiFilesBtn)
        clusterArch.setTabOrder(self.addNcbiFilesBtn, self.ncbiFileDLlist)
        clusterArch.setTabOrder(self.ncbiFileDLlist, self.ncbiFileDlDir)
        clusterArch.setTabOrder(self.ncbiFileDlDir, self.selectNcbiFileDirBtn)
        clusterArch.setTabOrder(self.selectNcbiFileDirBtn, self.removeNcbiFilesBtn)
        clusterArch.setTabOrder(self.removeNcbiFilesBtn, self.dlNcbiFilesBtn)
        clusterArch.setTabOrder(self.dlNcbiFilesBtn, self.bctChk)
        clusterArch.setTabOrder(self.bctChk, self.envChk)
        clusterArch.setTabOrder(self.envChk, self.gssChk)
        clusterArch.setTabOrder(self.gssChk, self.htgChk)
        clusterArch.setTabOrder(self.htgChk, self.invChk)
        clusterArch.setTabOrder(self.invChk, self.mamChk)
        clusterArch.setTabOrder(self.mamChk, self.patChk)
        clusterArch.setTabOrder(self.patChk, self.plnChk)
        clusterArch.setTabOrder(self.plnChk, self.priChk)
        clusterArch.setTabOrder(self.priChk, self.rodChk)
        clusterArch.setTabOrder(self.rodChk, self.stsChk)
        clusterArch.setTabOrder(self.stsChk, self.synChk)
        clusterArch.setTabOrder(self.synChk, self.tsaChk)
        clusterArch.setTabOrder(self.tsaChk, self.vrlChk)
        clusterArch.setTabOrder(self.vrlChk, self.vrtChk)
        clusterArch.setTabOrder(self.vrtChk, self.gbDivDLoutputDir)
        clusterArch.setTabOrder(self.gbDivDLoutputDir, self.selectGbDivDirBtn)
        clusterArch.setTabOrder(self.selectGbDivDirBtn, self.downloadGbDivFileBtn)
        clusterArch.setTabOrder(self.downloadGbDivFileBtn, self.minLength)
        clusterArch.setTabOrder(self.minLength, self.maxLength)
        clusterArch.setTabOrder(self.maxLength, self.numEntries)

    def retranslateUi(self, clusterArch):
        _translate = QtCore.QCoreApplication.translate
        clusterArch.setWindowTitle(_translate("clusterArch", "clusterArch"))
        self.label_6.setText(_translate("clusterArch", "Keyword:"))
        self.label_7.setText(_translate("clusterArch", "Organism:"))
        self.label_8.setText(_translate("clusterArch", "Accession:"))
        self.searchNcbiBtn.setText(_translate("clusterArch", "Search"))
        self.label_15.setText(_translate("clusterArch", "Min Length (bp): "))
        self.label_17.setText(_translate("clusterArch", "Max Length (bp):"))
        self.label_18.setText(_translate("clusterArch", "Number Entries (Max 1000):"))
        self.label_9.setText(_translate("clusterArch", "Search Results:"))
        self.label_20.setText(_translate("clusterArch", "Selection Filter:"))
        self.clearSearchSelectionBtn.setText(_translate("clusterArch", "Clear Selection"))
        self.label_19.setText(_translate("clusterArch", "Total Results:"))
        self.totalSearchResults.setText(_translate("clusterArch", "     0"))
        self.addNcbiFilesBtn.setText(_translate("clusterArch", "Add to Download List"))
        self.label_10.setText(_translate("clusterArch", "Entries to Download:"))
        self.removeNcbiFilesBtn.setText(_translate("clusterArch", "Remove"))
        self.label_11.setText(_translate("clusterArch", "Total Files:"))
        self.ncbiDLtotalFilesCt.setText(_translate("clusterArch", "0"))
        self.label_13.setText(_translate("clusterArch", "Output Directory:"))
        self.selectNcbiFileDirBtn.setText(_translate("clusterArch", "Select"))
        self.dlNcbiFilesBtn.setText(_translate("clusterArch", "Download Files"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ncbiDL), _translate("clusterArch", "Find Genbanks on NCBI Server"))
        self.priChk.setText(_translate("clusterArch", "PRI: Primate"))
        self.vrtChk.setText(_translate("clusterArch", "VRT: Vertebrate"))
        self.stsChk.setText(_translate("clusterArch", "STS: Sequence Tagged Sites"))
        self.patChk.setText(_translate("clusterArch", "PAT: Patented Sequences"))
        self.envChk.setText(_translate("clusterArch", "ENV: Environmental"))
        self.invChk.setText(_translate("clusterArch", "INV: Invertebrates"))
        self.htgChk.setText(_translate("clusterArch", "HTG: High Throughput Genome"))
        self.rodChk.setText(_translate("clusterArch", "ROD: Rodent"))
        self.vrlChk.setText(_translate("clusterArch", "VRL: Viral"))
        self.synChk.setText(_translate("clusterArch", "SYN: Synthetic and Chimeric Sequences"))
        self.gssChk.setText(_translate("clusterArch", "GSS: Genome Survey Sequences"))
        self.plnChk.setText(_translate("clusterArch", "PLN: Plant and Fungi"))
        self.mamChk.setText(_translate("clusterArch", "MAM: Mammalian"))
        self.tsaChk.setText(_translate("clusterArch", "TSA: Transcriptome Shotgun Data"))
        self.bctChk.setText(_translate("clusterArch", "BCT: Bacteria"))
        self.label_14.setText(_translate("clusterArch", "Total Files to Download:"))
        self.totalFilesGbDiv.setText(_translate("clusterArch", "0"))
        self.label_16.setText(_translate("clusterArch", "Estimated Disk Space: "))
        self.estSize.setText(_translate("clusterArch", "0"))
        self.checkRequestBtn.setText(_translate("clusterArch", "Check Request"))
        self.label_12.setText(_translate("clusterArch", "Output Directory:"))
        self.selectGbDivDirBtn.setText(_translate("clusterArch", "Select Directory"))
        self.downloadGbDivFileBtn.setText(_translate("clusterArch", "Download"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ncbiDiv), _translate("clusterArch", "Make Database from Genbank Divisions"))
        self.gbkPathLabel.setText(_translate("clusterArch", "Genbank Files Directory:"))
        self.genbankDirBtn.setText(_translate("clusterArch", "Choose Directory"))
        self.addGenbankBtn.setText(_translate("clusterArch", "Add Genbanks to List"))
        self.label.setText(_translate("clusterArch", "Total Files to Process:"))
        self.totalFiles.setText(_translate("clusterArch", "0"))
        self.DatabasePathLabel.setText(_translate("clusterArch", "Database Output Target:"))
        self.chooseDBoutputDirBtn.setText(_translate("clusterArch", "Save Database As"))
        self.deleteGenbankBtn.setText(_translate("clusterArch", "Remove from List"))
        self.createDbBtn.setText(_translate("clusterArch", "Create Database"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.filesDB), _translate("clusterArch", "Make Database From Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prepareDatabase), _translate("clusterArch", "Prepare Database"))
        self.label_4.setText(_translate("clusterArch", "Genes"))
        self.addGenefilePathBtn.setText(_translate("clusterArch", "Select File"))
        self.addGenefileBtn.setText(_translate("clusterArch", "Process"))
        self.addGeneSeqBtn.setText(_translate("clusterArch", "Input Gene "))
        self.addGeneBtn.setText(_translate("clusterArch", "Add Gene"))
        self.clearGeneBtn.setText(_translate("clusterArch", "Clear List"))
        self.label_3.setText(_translate("clusterArch", "HMMs"))
        self.addHMMfilePathBtn.setText(_translate("clusterArch", "Select File"))
        self.addHMMfilebtn.setText(_translate("clusterArch", "Process"))
        self.addHMMbtn.setText(_translate("clusterArch", "Add HMMs"))
        self.clearHMMbtn.setText(_translate("clusterArch", "Clear List"))
        self.databaseLabel.setText(_translate("clusterArch", "Database to Query:"))
        self.dataBaseSelector.setItemText(0, _translate("clusterArch", "add database..."))
        self.label_5.setText(_translate("clusterArch", "Search List:"))
        item = self.searchList.horizontalHeaderItem(0)
        item.setText(_translate("clusterArch", "Gene or HMM"))
        item = self.searchList.horizontalHeaderItem(1)
        item.setText(_translate("clusterArch", "Name"))
        item = self.searchList.horizontalHeaderItem(2)
        item.setText(_translate("clusterArch", "Required"))
        self.removeSearchTermBtn.setText(_translate("clusterArch", "Remove Term"))
        self.label_2.setText(_translate("clusterArch", "Minimum Number of Hits"))
        self.databaseLabel_2.setText(_translate("clusterArch", "Output Directory:"))
        self.outputDirectorySelector.setItemText(0, _translate("clusterArch", "Select Directory..."))
        self.setParamsBtn.setText(_translate("clusterArch", "Search Settings"))
        self.runSearch.setText(_translate("clusterArch", "Run Search"))
        self.closeBtn.setText(_translate("clusterArch", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchtab), _translate("clusterArch", "Run Search"))
        self.menuFile.setTitle(_translate("clusterArch", "File"))
        self.menuClose.setTitle(_translate("clusterArch", "Close"))
        self.actionSet_Database.setText(_translate("clusterArch", "Set Database"))
        self.actionOpen_Gene_File.setText(_translate("clusterArch", "Open Gene File"))
        self.actionOpen_HMM_File.setText(_translate("clusterArch", "Open HMM File"))

