# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clusterArch(object):
    def setupUi(self, clusterArch):
        clusterArch.setObjectName("clusterArch")
        clusterArch.resize(866, 574)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(clusterArch.sizePolicy().hasHeightForWidth())
        clusterArch.setSizePolicy(sizePolicy)
        clusterArch.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(clusterArch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.prepareDatabase = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prepareDatabase.sizePolicy().hasHeightForWidth())
        self.prepareDatabase.setSizePolicy(sizePolicy)
        self.prepareDatabase.setObjectName("prepareDatabase")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.prepareDatabase)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gbkPathLabel = QtWidgets.QLabel(self.prepareDatabase)
        self.gbkPathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.gbkPathLabel.setObjectName("gbkPathLabel")
        self.horizontalLayout_3.addWidget(self.gbkPathLabel)
        self.genbankDirPath = QtWidgets.QLineEdit(self.prepareDatabase)
        self.genbankDirPath.setReadOnly(True)
        self.genbankDirPath.setClearButtonEnabled(True)
        self.genbankDirPath.setObjectName("genbankDirPath")
        self.horizontalLayout_3.addWidget(self.genbankDirPath)
        self.genbankDirBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.genbankDirBtn.setObjectName("genbankDirBtn")
        self.horizontalLayout_3.addWidget(self.genbankDirBtn)
        self.addGenbankBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.addGenbankBtn.setObjectName("addGenbankBtn")
        self.horizontalLayout_3.addWidget(self.addGenbankBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.genbankList = QtWidgets.QListWidget(self.prepareDatabase)
        self.genbankList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genbankList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.genbankList.setObjectName("genbankList")
        self.verticalLayout.addWidget(self.genbankList)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.prepareDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.totalFiles = QtWidgets.QLabel(self.prepareDatabase)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalFiles.setFont(font)
        self.totalFiles.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.totalFiles.setObjectName("totalFiles")
        self.horizontalLayout_6.addWidget(self.totalFiles)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DatabasePathLabel = QtWidgets.QLabel(self.prepareDatabase)
        self.DatabasePathLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.DatabasePathLabel.setObjectName("DatabasePathLabel")
        self.horizontalLayout_4.addWidget(self.DatabasePathLabel)
        self.dbOutputDir = QtWidgets.QLineEdit(self.prepareDatabase)
        self.dbOutputDir.setReadOnly(True)
        self.dbOutputDir.setClearButtonEnabled(True)
        self.dbOutputDir.setObjectName("dbOutputDir")
        self.horizontalLayout_4.addWidget(self.dbOutputDir)
        self.chooseDBoutputDirBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.chooseDBoutputDirBtn.setObjectName("chooseDBoutputDirBtn")
        self.horizontalLayout_4.addWidget(self.chooseDBoutputDirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deleteGenbankBtn = QtWidgets.QPushButton(self.prepareDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteGenbankBtn.sizePolicy().hasHeightForWidth())
        self.deleteGenbankBtn.setSizePolicy(sizePolicy)
        self.deleteGenbankBtn.setObjectName("deleteGenbankBtn")
        self.horizontalLayout_2.addWidget(self.deleteGenbankBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.createDbBtn = QtWidgets.QPushButton(self.prepareDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDbBtn.sizePolicy().hasHeightForWidth())
        self.createDbBtn.setSizePolicy(sizePolicy)
        self.createDbBtn.setObjectName("createDbBtn")
        self.horizontalLayout_2.addWidget(self.createDbBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.prepareDatabase, "")
        self.searchtab = QtWidgets.QWidget()
        self.searchtab.setObjectName("searchtab")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.searchtab)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.GeneFilePath = QtWidgets.QLineEdit(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneFilePath.sizePolicy().hasHeightForWidth())
        self.GeneFilePath.setSizePolicy(sizePolicy)
        self.GeneFilePath.setReadOnly(True)
        self.GeneFilePath.setObjectName("GeneFilePath")
        self.horizontalLayout_8.addWidget(self.GeneFilePath)
        self.addGenefilePathBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefilePathBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGenefilePathBtn.sizePolicy().hasHeightForWidth())
        self.addGenefilePathBtn.setSizePolicy(sizePolicy)
        self.addGenefilePathBtn.setObjectName("addGenefilePathBtn")
        self.horizontalLayout_8.addWidget(self.addGenefilePathBtn)
        self.addGenefileBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefileBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGenefileBtn.sizePolicy().hasHeightForWidth())
        self.addGenefileBtn.setSizePolicy(sizePolicy)
        self.addGenefileBtn.setObjectName("addGenefileBtn")
        self.horizontalLayout_8.addWidget(self.addGenefileBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.geneList = QtWidgets.QListWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geneList.sizePolicy().hasHeightForWidth())
        self.geneList.setSizePolicy(sizePolicy)
        self.geneList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.geneList.setObjectName("geneList")
        self.horizontalLayout_10.addWidget(self.geneList)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.addGeneSeqBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGeneSeqBtn.sizePolicy().hasHeightForWidth())
        self.addGeneSeqBtn.setSizePolicy(sizePolicy)
        self.addGeneSeqBtn.setObjectName("addGeneSeqBtn")
        self.verticalLayout_7.addWidget(self.addGeneSeqBtn)
        self.addGeneBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGeneBtn.sizePolicy().hasHeightForWidth())
        self.addGeneBtn.setSizePolicy(sizePolicy)
        self.addGeneBtn.setObjectName("addGeneBtn")
        self.verticalLayout_7.addWidget(self.addGeneBtn)
        self.clearGeneBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearGeneBtn.sizePolicy().hasHeightForWidth())
        self.clearGeneBtn.setSizePolicy(sizePolicy)
        self.clearGeneBtn.setObjectName("clearGeneBtn")
        self.verticalLayout_7.addWidget(self.clearGeneBtn)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.line_2 = QtWidgets.QFrame(self.searchtab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.hmmFilePath = QtWidgets.QLineEdit(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmmFilePath.sizePolicy().hasHeightForWidth())
        self.hmmFilePath.setSizePolicy(sizePolicy)
        self.hmmFilePath.setObjectName("hmmFilePath")
        self.horizontalLayout_11.addWidget(self.hmmFilePath)
        self.addHMMfilePathBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMfilePathBtn.sizePolicy().hasHeightForWidth())
        self.addHMMfilePathBtn.setSizePolicy(sizePolicy)
        self.addHMMfilePathBtn.setObjectName("addHMMfilePathBtn")
        self.horizontalLayout_11.addWidget(self.addHMMfilePathBtn)
        self.addHMMfilebtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMfilebtn.sizePolicy().hasHeightForWidth())
        self.addHMMfilebtn.setSizePolicy(sizePolicy)
        self.addHMMfilebtn.setObjectName("addHMMfilebtn")
        self.horizontalLayout_11.addWidget(self.addHMMfilebtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.hmmList = QtWidgets.QListWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmmList.sizePolicy().hasHeightForWidth())
        self.hmmList.setSizePolicy(sizePolicy)
        self.hmmList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.hmmList.setObjectName("hmmList")
        self.horizontalLayout_12.addWidget(self.hmmList)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.addHMMbtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addHMMbtn.sizePolicy().hasHeightForWidth())
        self.addHMMbtn.setSizePolicy(sizePolicy)
        self.addHMMbtn.setObjectName("addHMMbtn")
        self.verticalLayout_8.addWidget(self.addHMMbtn)
        self.clearHMMbtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearHMMbtn.sizePolicy().hasHeightForWidth())
        self.clearHMMbtn.setSizePolicy(sizePolicy)
        self.clearHMMbtn.setObjectName("clearHMMbtn")
        self.verticalLayout_8.addWidget(self.clearHMMbtn)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_12.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.line_6 = QtWidgets.QFrame(self.searchtab)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_13.addWidget(self.line_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.databaseLabel = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel.setObjectName("databaseLabel")
        self.horizontalLayout.addWidget(self.databaseLabel)
        self.dataBaseSelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataBaseSelector.sizePolicy().hasHeightForWidth())
        self.dataBaseSelector.setSizePolicy(sizePolicy)
        self.dataBaseSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.dataBaseSelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.dataBaseSelector.setObjectName("dataBaseSelector")
        self.dataBaseSelector.addItem("")
        self.horizontalLayout.addWidget(self.dataBaseSelector)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.searchtab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.searchtab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.searchList = QtWidgets.QTableWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchList.sizePolicy().hasHeightForWidth())
        self.searchList.setSizePolicy(sizePolicy)
        self.searchList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.searchList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchList.setColumnCount(3)
        self.searchList.setObjectName("searchList")
        self.searchList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(2, item)
        self.searchList.horizontalHeader().setCascadingSectionResizes(True)
        self.searchList.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.searchList)
        self.removeSearchTermBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeSearchTermBtn.sizePolicy().hasHeightForWidth())
        self.removeSearchTermBtn.setSizePolicy(sizePolicy)
        self.removeSearchTermBtn.setObjectName("removeSearchTermBtn")
        self.verticalLayout_3.addWidget(self.removeSearchTermBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.searchtab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.searchtab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self.searchtab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.hitsNeededSpinBox = QtWidgets.QSpinBox(self.searchtab)
        self.hitsNeededSpinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hitsNeededSpinBox.sizePolicy().hasHeightForWidth())
        self.hitsNeededSpinBox.setSizePolicy(sizePolicy)
        self.hitsNeededSpinBox.setObjectName("hitsNeededSpinBox")
        self.horizontalLayout_7.addWidget(self.hitsNeededSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.searchtab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.databaseLabel_2 = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.horizontalLayout_9.addWidget(self.databaseLabel_2)
        self.outputDirectorySelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectorySelector.sizePolicy().hasHeightForWidth())
        self.outputDirectorySelector.setSizePolicy(sizePolicy)
        self.outputDirectorySelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.outputDirectorySelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.outputDirectorySelector.setObjectName("outputDirectorySelector")
        self.outputDirectorySelector.addItem("")
        self.horizontalLayout_9.addWidget(self.outputDirectorySelector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setParamsBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setParamsBtn.sizePolicy().hasHeightForWidth())
        self.setParamsBtn.setSizePolicy(sizePolicy)
        self.setParamsBtn.setObjectName("setParamsBtn")
        self.horizontalLayout_5.addWidget(self.setParamsBtn)
        self.runSearch = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runSearch.sizePolicy().hasHeightForWidth())
        self.runSearch.setSizePolicy(sizePolicy)
        self.runSearch.setObjectName("runSearch")
        self.horizontalLayout_5.addWidget(self.runSearch, 0, QtCore.Qt.AlignLeft)
        self.closeBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_5.addWidget(self.closeBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.searchtab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        clusterArch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clusterArch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        clusterArch.setMenuBar(self.menubar)
        self.actionSet_Database = QtWidgets.QAction(clusterArch)
        self.actionSet_Database.setObjectName("actionSet_Database")
        self.actionOpen_Gene_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_Gene_File.setObjectName("actionOpen_Gene_File")
        self.actionOpen_HMM_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_HMM_File.setObjectName("actionOpen_HMM_File")
        self.menuFile.addAction(self.actionSet_Database)
        self.menuFile.addAction(self.actionOpen_Gene_File)
        self.menuFile.addAction(self.actionOpen_HMM_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(clusterArch)
        self.tabWidget.setCurrentIndex(1)
        self.dataBaseSelector.setCurrentIndex(-1)
        self.outputDirectorySelector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(clusterArch)

    def retranslateUi(self, clusterArch):
        _translate = QtCore.QCoreApplication.translate
        clusterArch.setWindowTitle(_translate("clusterArch", "clusterArch"))
        self.gbkPathLabel.setText(_translate("clusterArch", "Genbank Files Directory:"))
        self.genbankDirBtn.setText(_translate("clusterArch", "Choose Directory"))
        self.addGenbankBtn.setText(_translate("clusterArch", "Add Genbanks to List"))
        self.label.setText(_translate("clusterArch", "Total Files to Process:"))
        self.totalFiles.setText(_translate("clusterArch", "0"))
        self.DatabasePathLabel.setText(_translate("clusterArch", "Database Output Path:"))
        self.chooseDBoutputDirBtn.setText(_translate("clusterArch", "Choose Directory"))
        self.deleteGenbankBtn.setText(_translate("clusterArch", "Remove from List"))
        self.createDbBtn.setText(_translate("clusterArch", "Create Database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prepareDatabase), _translate("clusterArch", "Prepare Database"))
        self.label_4.setText(_translate("clusterArch", "Genes"))
        self.addGenefilePathBtn.setText(_translate("clusterArch", "Select File"))
        self.addGenefileBtn.setText(_translate("clusterArch", "Process"))
        self.addGeneSeqBtn.setText(_translate("clusterArch", "Input Gene "))
        self.addGeneBtn.setText(_translate("clusterArch", "Add Gene"))
        self.clearGeneBtn.setText(_translate("clusterArch", "Clear List"))
        self.label_3.setText(_translate("clusterArch", "HMMs"))
        self.addHMMfilePathBtn.setText(_translate("clusterArch", "Select File"))
        self.addHMMfilebtn.setText(_translate("clusterArch", "Process"))
        self.addHMMbtn.setText(_translate("clusterArch", "Add HMMs"))
        self.clearHMMbtn.setText(_translate("clusterArch", "Clear List"))
        self.databaseLabel.setText(_translate("clusterArch", "Database to Query:"))
        self.dataBaseSelector.setItemText(0, _translate("clusterArch", "add database..."))
        self.label_5.setText(_translate("clusterArch", "Search List:"))
        item = self.searchList.horizontalHeaderItem(0)
        item.setText(_translate("clusterArch", "Gene or HMM"))
        item = self.searchList.horizontalHeaderItem(1)
        item.setText(_translate("clusterArch", "Name"))
        item = self.searchList.horizontalHeaderItem(2)
        item.setText(_translate("clusterArch", "Required"))
        self.removeSearchTermBtn.setText(_translate("clusterArch", "Remove Term"))
        self.label_2.setText(_translate("clusterArch", "Minimum Number of Hits"))
        self.databaseLabel_2.setText(_translate("clusterArch", "Output Directory:"))
        self.outputDirectorySelector.setItemText(0, _translate("clusterArch", "Select Directory..."))
        self.setParamsBtn.setText(_translate("clusterArch", "Search Settings"))
        self.runSearch.setText(_translate("clusterArch", "Run Search"))
        self.closeBtn.setText(_translate("clusterArch", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchtab), _translate("clusterArch", "Run Search"))
        self.menuFile.setTitle(_translate("clusterArch", "File"))
        self.menuClose.setTitle(_translate("clusterArch", "Close"))
        self.actionSet_Database.setText(_translate("clusterArch", "Set Database"))
        self.actionOpen_Gene_File.setText(_translate("clusterArch", "Open Gene File"))
        self.actionOpen_HMM_File.setText(_translate("clusterArch", "Open HMM File"))

