# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clusterArch(object):
    def setupUi(self, clusterArch):
        clusterArch.setObjectName("clusterArch")
        clusterArch.resize(822, 618)
        clusterArch.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(clusterArch)
        self.centralwidget.setObjectName("centralwidget")
        self.addGenefileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGenefileBtn.setEnabled(True)
        self.addGenefileBtn.setGeometry(QtCore.QRect(200, 40, 111, 21))
        self.addGenefileBtn.setObjectName("addGenefileBtn")
        self.addHMMfilebtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMfilebtn.setGeometry(QtCore.QRect(200, 300, 111, 21))
        self.addHMMfilebtn.setObjectName("addHMMfilebtn")
        self.addHMMbtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMbtn.setGeometry(QtCore.QRect(30, 500, 111, 21))
        self.addHMMbtn.setObjectName("addHMMbtn")
        self.geneList = QtWidgets.QListWidget(self.centralwidget)
        self.geneList.setGeometry(QtCore.QRect(30, 71, 281, 171))
        self.geneList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.geneList.setObjectName("geneList")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(680, 520, 91, 21))
        self.closeBtn.setObjectName("closeBtn")
        self.clearGeneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearGeneBtn.setGeometry(QtCore.QRect(210, 250, 101, 21))
        self.clearGeneBtn.setObjectName("clearGeneBtn")
        self.clearHMMbtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearHMMbtn.setGeometry(QtCore.QRect(210, 500, 101, 21))
        self.clearHMMbtn.setObjectName("clearHMMbtn")
        self.addGeneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGeneBtn.setGeometry(QtCore.QRect(30, 250, 111, 21))
        self.addGeneBtn.setObjectName("addGeneBtn")
        self.hmmList = QtWidgets.QListWidget(self.centralwidget)
        self.hmmList.setGeometry(QtCore.QRect(30, 330, 281, 171))
        self.hmmList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.hmmList.setObjectName("hmmList")
        self.hmmFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.hmmFilePath.setGeometry(QtCore.QRect(30, 280, 281, 21))
        self.hmmFilePath.setObjectName("hmmFilePath")
        self.addHMMfilePathBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMfilePathBtn.setGeometry(QtCore.QRect(30, 300, 111, 21))
        self.addHMMfilePathBtn.setObjectName("addHMMfilePathBtn")
        self.GeneFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.GeneFilePath.setGeometry(QtCore.QRect(30, 20, 281, 21))
        self.GeneFilePath.setReadOnly(True)
        self.GeneFilePath.setObjectName("GeneFilePath")
        self.addGenefilePathBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGenefilePathBtn.setEnabled(True)
        self.addGenefilePathBtn.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.addGenefilePathBtn.setObjectName("addGenefilePathBtn")
        self.searchList = QtWidgets.QTableWidget(self.centralwidget)
        self.searchList.setGeometry(QtCore.QRect(320, 20, 451, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchList.sizePolicy().hasHeightForWidth())
        self.searchList.setSizePolicy(sizePolicy)
        self.searchList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.searchList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchList.setColumnCount(2)
        self.searchList.setObjectName("searchList")
        self.searchList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(1, item)
        self.dataBaseSelector = QtWidgets.QComboBox(self.centralwidget)
        self.dataBaseSelector.setGeometry(QtCore.QRect(440, 450, 331, 21))
        self.dataBaseSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.dataBaseSelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.dataBaseSelector.setObjectName("dataBaseSelector")
        self.dataBaseSelector.addItem("")
        self.databaseLabel = QtWidgets.QLabel(self.centralwidget)
        self.databaseLabel.setGeometry(QtCore.QRect(320, 450, 121, 21))
        self.databaseLabel.setObjectName("databaseLabel")
        self.runSearch = QtWidgets.QPushButton(self.centralwidget)
        self.runSearch.setGeometry(QtCore.QRect(560, 520, 111, 21))
        self.runSearch.setObjectName("runSearch")
        self.removeSearchTermBtn = QtWidgets.QPushButton(self.centralwidget)
        self.removeSearchTermBtn.setGeometry(QtCore.QRect(650, 410, 121, 21))
        self.removeSearchTermBtn.setObjectName("removeSearchTermBtn")
        self.databaseLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.databaseLabel_2.setGeometry(QtCore.QRect(330, 480, 111, 21))
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.outputDirectorySelector = QtWidgets.QComboBox(self.centralwidget)
        self.outputDirectorySelector.setGeometry(QtCore.QRect(440, 480, 331, 21))
        self.outputDirectorySelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.outputDirectorySelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.outputDirectorySelector.setObjectName("outputDirectorySelector")
        self.outputDirectorySelector.addItem("")
        clusterArch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clusterArch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        clusterArch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(clusterArch)
        self.statusbar.setObjectName("statusbar")
        clusterArch.setStatusBar(self.statusbar)
        self.actionSet_Database = QtWidgets.QAction(clusterArch)
        self.actionSet_Database.setObjectName("actionSet_Database")
        self.actionOpen_Gene_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_Gene_File.setObjectName("actionOpen_Gene_File")
        self.actionOpen_HMM_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_HMM_File.setObjectName("actionOpen_HMM_File")
        self.menuFile.addAction(self.actionSet_Database)
        self.menuFile.addAction(self.actionOpen_Gene_File)
        self.menuFile.addAction(self.actionOpen_HMM_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(clusterArch)
        self.dataBaseSelector.setCurrentIndex(-1)
        self.outputDirectorySelector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(clusterArch)

    def retranslateUi(self, clusterArch):
        _translate = QtCore.QCoreApplication.translate
        clusterArch.setWindowTitle(_translate("clusterArch", "clusterArch"))
        self.addGenefileBtn.setText(_translate("clusterArch", "Parse Gene File"))
        self.addHMMfilebtn.setText(_translate("clusterArch", "Parse HMM FIle"))
        self.addHMMbtn.setText(_translate("clusterArch", "add HMM hits"))
        self.closeBtn.setText(_translate("clusterArch", "Close"))
        self.clearGeneBtn.setText(_translate("clusterArch", "clear"))
        self.clearHMMbtn.setText(_translate("clusterArch", "clear"))
        self.addGeneBtn.setText(_translate("clusterArch", "add Gene"))
        self.addHMMfilePathBtn.setText(_translate("clusterArch", "HMM File Path"))
        self.addGenefilePathBtn.setText(_translate("clusterArch", "Gene File Path"))
        item = self.searchList.horizontalHeaderItem(0)
        item.setText(_translate("clusterArch", "Gene or HMM"))
        item = self.searchList.horizontalHeaderItem(1)
        item.setText(_translate("clusterArch", "Name"))
        self.dataBaseSelector.setItemText(0, _translate("clusterArch", "add database..."))
        self.databaseLabel.setText(_translate("clusterArch", "Database to Query:"))
        self.runSearch.setText(_translate("clusterArch", "Run Search"))
        self.removeSearchTermBtn.setText(_translate("clusterArch", "Remove Term"))
        self.databaseLabel_2.setText(_translate("clusterArch", "Output Directory:"))
        self.outputDirectorySelector.setItemText(0, _translate("clusterArch", "Select Directory..."))
        self.menuFile.setTitle(_translate("clusterArch", "File"))
        self.menuClose.setTitle(_translate("clusterArch", "Close"))
        self.actionSet_Database.setText(_translate("clusterArch", "Set Database"))
        self.actionOpen_Gene_File.setText(_translate("clusterArch", "Open Gene File"))
        self.actionOpen_HMM_File.setText(_translate("clusterArch", "Open HMM File"))

