# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clusterArch(object):
    def setupUi(self, clusterArch):
        clusterArch.setObjectName("clusterArch")
        clusterArch.resize(914, 624)
        clusterArch.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(clusterArch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.prepareDatabase = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prepareDatabase.sizePolicy().hasHeightForWidth())
        self.prepareDatabase.setSizePolicy(sizePolicy)
        self.prepareDatabase.setObjectName("prepareDatabase")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.prepareDatabase)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gbkPathLabel = QtWidgets.QLabel(self.prepareDatabase)
        self.gbkPathLabel.setObjectName("gbkPathLabel")
        self.horizontalLayout_3.addWidget(self.gbkPathLabel)
        self.genbankDirPath = QtWidgets.QLineEdit(self.prepareDatabase)
        self.genbankDirPath.setReadOnly(True)
        self.genbankDirPath.setClearButtonEnabled(True)
        self.genbankDirPath.setObjectName("genbankDirPath")
        self.horizontalLayout_3.addWidget(self.genbankDirPath)
        self.genbankDirBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.genbankDirBtn.setObjectName("genbankDirBtn")
        self.horizontalLayout_3.addWidget(self.genbankDirBtn)
        self.addGenbankBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.addGenbankBtn.setObjectName("addGenbankBtn")
        self.horizontalLayout_3.addWidget(self.addGenbankBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.genbankList = QtWidgets.QListWidget(self.prepareDatabase)
        self.genbankList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.genbankList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.genbankList.setObjectName("genbankList")
        self.verticalLayout.addWidget(self.genbankList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DatabasePathLabel = QtWidgets.QLabel(self.prepareDatabase)
        self.DatabasePathLabel.setObjectName("DatabasePathLabel")
        self.horizontalLayout_4.addWidget(self.DatabasePathLabel)
        self.dbOutputDir = QtWidgets.QLineEdit(self.prepareDatabase)
        self.dbOutputDir.setReadOnly(True)
        self.dbOutputDir.setClearButtonEnabled(True)
        self.dbOutputDir.setObjectName("dbOutputDir")
        self.horizontalLayout_4.addWidget(self.dbOutputDir)
        self.chooseDBoutputDirBtn = QtWidgets.QPushButton(self.prepareDatabase)
        self.chooseDBoutputDirBtn.setObjectName("chooseDBoutputDirBtn")
        self.horizontalLayout_4.addWidget(self.chooseDBoutputDirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deleteGenbankBtn = QtWidgets.QPushButton(self.prepareDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteGenbankBtn.sizePolicy().hasHeightForWidth())
        self.deleteGenbankBtn.setSizePolicy(sizePolicy)
        self.deleteGenbankBtn.setObjectName("deleteGenbankBtn")
        self.horizontalLayout_2.addWidget(self.deleteGenbankBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.createDbBtn = QtWidgets.QPushButton(self.prepareDatabase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDbBtn.sizePolicy().hasHeightForWidth())
        self.createDbBtn.setSizePolicy(sizePolicy)
        self.createDbBtn.setObjectName("createDbBtn")
        self.horizontalLayout_2.addWidget(self.createDbBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.prepareDatabase, "")
        self.searchtab = QtWidgets.QWidget()
        self.searchtab.setObjectName("searchtab")
        self.gridLayout = QtWidgets.QGridLayout(self.searchtab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.databaseLabel = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel.setObjectName("databaseLabel")
        self.gridLayout.addWidget(self.databaseLabel, 2, 5, 1, 1)
        self.addHMMbtn = QtWidgets.QPushButton(self.searchtab)
        self.addHMMbtn.setObjectName("addHMMbtn")
        self.gridLayout.addWidget(self.addHMMbtn, 23, 0, 1, 1)
        self.addHMMfilePathBtn = QtWidgets.QPushButton(self.searchtab)
        self.addHMMfilePathBtn.setObjectName("addHMMfilePathBtn")
        self.gridLayout.addWidget(self.addHMMfilePathBtn, 17, 0, 1, 1)
        self.addGenefileBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefileBtn.setEnabled(True)
        self.addGenefileBtn.setObjectName("addGenefileBtn")
        self.gridLayout.addWidget(self.addGenefileBtn, 3, 1, 1, 1)
        self.clearHMMbtn = QtWidgets.QPushButton(self.searchtab)
        self.clearHMMbtn.setObjectName("clearHMMbtn")
        self.gridLayout.addWidget(self.clearHMMbtn, 23, 1, 1, 1)
        self.addGeneBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGeneBtn.setObjectName("addGeneBtn")
        self.gridLayout.addWidget(self.addGeneBtn, 11, 0, 1, 1)
        self.geneList = QtWidgets.QListWidget(self.searchtab)
        self.geneList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.geneList.setObjectName("geneList")
        self.gridLayout.addWidget(self.geneList, 10, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchList = QtWidgets.QTableWidget(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchList.sizePolicy().hasHeightForWidth())
        self.searchList.setSizePolicy(sizePolicy)
        self.searchList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.searchList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.searchList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchList.setColumnCount(2)
        self.searchList.setObjectName("searchList")
        self.searchList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(1, item)
        self.searchList.horizontalHeader().setCascadingSectionResizes(True)
        self.searchList.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.searchList)
        self.removeSearchTermBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeSearchTermBtn.sizePolicy().hasHeightForWidth())
        self.removeSearchTermBtn.setSizePolicy(sizePolicy)
        self.removeSearchTermBtn.setObjectName("removeSearchTermBtn")
        self.verticalLayout_3.addWidget(self.removeSearchTermBtn)
        self.gridLayout.addLayout(self.verticalLayout_3, 10, 5, 2, 1)
        self.hmmList = QtWidgets.QListWidget(self.searchtab)
        self.hmmList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.hmmList.setObjectName("hmmList")
        self.gridLayout.addWidget(self.hmmList, 19, 0, 1, 2)
        self.hmmFilePath = QtWidgets.QLineEdit(self.searchtab)
        self.hmmFilePath.setObjectName("hmmFilePath")
        self.gridLayout.addWidget(self.hmmFilePath, 15, 0, 1, 2)
        self.GeneFilePath = QtWidgets.QLineEdit(self.searchtab)
        self.GeneFilePath.setReadOnly(True)
        self.GeneFilePath.setObjectName("GeneFilePath")
        self.gridLayout.addWidget(self.GeneFilePath, 2, 0, 1, 2)
        self.dataBaseSelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataBaseSelector.sizePolicy().hasHeightForWidth())
        self.dataBaseSelector.setSizePolicy(sizePolicy)
        self.dataBaseSelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.dataBaseSelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.dataBaseSelector.setObjectName("dataBaseSelector")
        self.dataBaseSelector.addItem("")
        self.gridLayout.addWidget(self.dataBaseSelector, 3, 5, 1, 1)
        self.addGenefilePathBtn = QtWidgets.QPushButton(self.searchtab)
        self.addGenefilePathBtn.setEnabled(True)
        self.addGenefilePathBtn.setObjectName("addGenefilePathBtn")
        self.gridLayout.addWidget(self.addGenefilePathBtn, 3, 0, 1, 1)
        self.addHMMfilebtn = QtWidgets.QPushButton(self.searchtab)
        self.addHMMfilebtn.setObjectName("addHMMfilebtn")
        self.gridLayout.addWidget(self.addHMMfilebtn, 17, 1, 1, 1)
        self.clearGeneBtn = QtWidgets.QPushButton(self.searchtab)
        self.clearGeneBtn.setObjectName("clearGeneBtn")
        self.gridLayout.addWidget(self.clearGeneBtn, 11, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.databaseLabel_2 = QtWidgets.QLabel(self.searchtab)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.verticalLayout_2.addWidget(self.databaseLabel_2)
        self.outputDirectorySelector = QtWidgets.QComboBox(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectorySelector.sizePolicy().hasHeightForWidth())
        self.outputDirectorySelector.setSizePolicy(sizePolicy)
        self.outputDirectorySelector.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.outputDirectorySelector.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.outputDirectorySelector.setObjectName("outputDirectorySelector")
        self.outputDirectorySelector.addItem("")
        self.verticalLayout_2.addWidget(self.outputDirectorySelector, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.setParamsBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setParamsBtn.sizePolicy().hasHeightForWidth())
        self.setParamsBtn.setSizePolicy(sizePolicy)
        self.setParamsBtn.setObjectName("setParamsBtn")
        self.horizontalLayout_5.addWidget(self.setParamsBtn)
        self.runSearch = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runSearch.sizePolicy().hasHeightForWidth())
        self.runSearch.setSizePolicy(sizePolicy)
        self.runSearch.setObjectName("runSearch")
        self.horizontalLayout_5.addWidget(self.runSearch, 0, QtCore.Qt.AlignLeft)
        self.closeBtn = QtWidgets.QPushButton(self.searchtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_5.addWidget(self.closeBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 19, 5, 1, 1)
        self.tabWidget.addTab(self.searchtab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        clusterArch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clusterArch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        clusterArch.setMenuBar(self.menubar)
        self.actionSet_Database = QtWidgets.QAction(clusterArch)
        self.actionSet_Database.setObjectName("actionSet_Database")
        self.actionOpen_Gene_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_Gene_File.setObjectName("actionOpen_Gene_File")
        self.actionOpen_HMM_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_HMM_File.setObjectName("actionOpen_HMM_File")
        self.menuFile.addAction(self.actionSet_Database)
        self.menuFile.addAction(self.actionOpen_Gene_File)
        self.menuFile.addAction(self.actionOpen_HMM_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(clusterArch)
        self.tabWidget.setCurrentIndex(0)
        self.dataBaseSelector.setCurrentIndex(-1)
        self.outputDirectorySelector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(clusterArch)

    def retranslateUi(self, clusterArch):
        _translate = QtCore.QCoreApplication.translate
        clusterArch.setWindowTitle(_translate("clusterArch", "clusterArch"))
        self.gbkPathLabel.setText(_translate("clusterArch", "Genbank Files Directory:"))
        self.genbankDirBtn.setText(_translate("clusterArch", "Choose Directory"))
        self.addGenbankBtn.setText(_translate("clusterArch", "Add Genbanks to List"))
        self.DatabasePathLabel.setText(_translate("clusterArch", "Database Output Path:"))
        self.chooseDBoutputDirBtn.setText(_translate("clusterArch", "Choose Directory"))
        self.deleteGenbankBtn.setText(_translate("clusterArch", "Remove from List"))
        self.createDbBtn.setText(_translate("clusterArch", "Create Database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prepareDatabase), _translate("clusterArch", "Prepare Database"))
        self.databaseLabel.setText(_translate("clusterArch", "Database to Query:"))
        self.addHMMbtn.setText(_translate("clusterArch", "add HMM hits"))
        self.addHMMfilePathBtn.setText(_translate("clusterArch", "HMM File Path"))
        self.addGenefileBtn.setText(_translate("clusterArch", "Process Gene File"))
        self.clearHMMbtn.setText(_translate("clusterArch", "clear"))
        self.addGeneBtn.setText(_translate("clusterArch", "add Gene"))
        item = self.searchList.horizontalHeaderItem(0)
        item.setText(_translate("clusterArch", "Gene or HMM"))
        item = self.searchList.horizontalHeaderItem(1)
        item.setText(_translate("clusterArch", "Name"))
        self.removeSearchTermBtn.setText(_translate("clusterArch", "Remove Term"))
        self.dataBaseSelector.setItemText(0, _translate("clusterArch", "add database..."))
        self.addGenefilePathBtn.setText(_translate("clusterArch", "Gene File Path"))
        self.addHMMfilebtn.setText(_translate("clusterArch", "Process HMM FIle"))
        self.clearGeneBtn.setText(_translate("clusterArch", "clear"))
        self.databaseLabel_2.setText(_translate("clusterArch", "Output Directory:"))
        self.outputDirectorySelector.setItemText(0, _translate("clusterArch", "Select Directory..."))
        self.setParamsBtn.setText(_translate("clusterArch", "Search Settings"))
        self.runSearch.setText(_translate("clusterArch", "Run Search"))
        self.closeBtn.setText(_translate("clusterArch", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchtab), _translate("clusterArch", "Run Search"))
        self.menuFile.setTitle(_translate("clusterArch", "File"))
        self.menuClose.setTitle(_translate("clusterArch", "Close"))
        self.actionSet_Database.setText(_translate("clusterArch", "Set Database"))
        self.actionOpen_Gene_File.setText(_translate("clusterArch", "Open Gene File"))
        self.actionOpen_HMM_File.setText(_translate("clusterArch", "Open HMM File"))

