# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_clusterArch(object):
    def setupUi(self, clusterArch):
        clusterArch.setObjectName("clusterArch")
        clusterArch.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(clusterArch)
        self.centralwidget.setObjectName("centralwidget")
        self.addGenefileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGenefileBtn.setEnabled(True)
        self.addGenefileBtn.setGeometry(QtCore.QRect(200, 40, 111, 21))
        self.addGenefileBtn.setObjectName("addGenefileBtn")
        self.addHMMfilebtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMfilebtn.setGeometry(QtCore.QRect(200, 290, 111, 21))
        self.addHMMfilebtn.setObjectName("addHMMfilebtn")
        self.addHMMbtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMbtn.setGeometry(QtCore.QRect(30, 490, 101, 23))
        self.addHMMbtn.setObjectName("addHMMbtn")
        self.geneList = QtWidgets.QListWidget(self.centralwidget)
        self.geneList.setGeometry(QtCore.QRect(30, 71, 281, 171))
        self.geneList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.geneList.setObjectName("geneList")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(690, 480, 101, 23))
        self.closeBtn.setObjectName("closeBtn")
        self.clearGeneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearGeneBtn.setGeometry(QtCore.QRect(210, 240, 101, 23))
        self.clearGeneBtn.setObjectName("clearGeneBtn")
        self.clearHMMbtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearHMMbtn.setGeometry(QtCore.QRect(210, 490, 101, 23))
        self.clearHMMbtn.setObjectName("clearHMMbtn")
        self.addGeneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGeneBtn.setGeometry(QtCore.QRect(30, 240, 101, 23))
        self.addGeneBtn.setObjectName("addGeneBtn")
        self.hmmList = QtWidgets.QListWidget(self.centralwidget)
        self.hmmList.setGeometry(QtCore.QRect(30, 321, 281, 171))
        self.hmmList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.hmmList.setObjectName("hmmList")
        self.hmmFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.hmmFilePath.setGeometry(QtCore.QRect(30, 270, 281, 21))
        self.hmmFilePath.setObjectName("hmmFilePath")
        self.addHMMfilePathBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addHMMfilePathBtn.setGeometry(QtCore.QRect(30, 290, 111, 21))
        self.addHMMfilePathBtn.setObjectName("addHMMfilePathBtn")
        self.GeneFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.GeneFilePath.setGeometry(QtCore.QRect(30, 20, 281, 21))
        self.GeneFilePath.setReadOnly(True)
        self.GeneFilePath.setObjectName("GeneFilePath")
        self.addGenefilePathBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addGenefilePathBtn.setEnabled(True)
        self.addGenefilePathBtn.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.addGenefilePathBtn.setObjectName("addGenefilePathBtn")
        self.searchList = QtWidgets.QTableWidget(self.centralwidget)
        self.searchList.setGeometry(QtCore.QRect(410, 60, 371, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchList.sizePolicy().hasHeightForWidth())
        self.searchList.setSizePolicy(sizePolicy)
        self.searchList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.searchList.setColumnCount(2)
        self.searchList.setObjectName("searchList")
        self.searchList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchList.setHorizontalHeaderItem(1, item)
        clusterArch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(clusterArch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClose = QtWidgets.QMenu(self.menubar)
        self.menuClose.setObjectName("menuClose")
        clusterArch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(clusterArch)
        self.statusbar.setObjectName("statusbar")
        clusterArch.setStatusBar(self.statusbar)
        self.actionSet_Database = QtWidgets.QAction(clusterArch)
        self.actionSet_Database.setObjectName("actionSet_Database")
        self.actionOpen_Gene_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_Gene_File.setObjectName("actionOpen_Gene_File")
        self.actionOpen_HMM_File = QtWidgets.QAction(clusterArch)
        self.actionOpen_HMM_File.setObjectName("actionOpen_HMM_File")
        self.menuFile.addAction(self.actionSet_Database)
        self.menuFile.addAction(self.actionOpen_Gene_File)
        self.menuFile.addAction(self.actionOpen_HMM_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClose.menuAction())

        self.retranslateUi(clusterArch)
        QtCore.QMetaObject.connectSlotsByName(clusterArch)

    def retranslateUi(self, clusterArch):
        _translate = QtCore.QCoreApplication.translate
        clusterArch.setWindowTitle(_translate("clusterArch", "clusterArch"))
        self.addGenefileBtn.setText(_translate("clusterArch", "Parse Gene File"))
        self.addHMMfilebtn.setText(_translate("clusterArch", "Parse HMM FIle"))
        self.addHMMbtn.setText(_translate("clusterArch", "add"))
        self.closeBtn.setText(_translate("clusterArch", "close"))
        self.clearGeneBtn.setText(_translate("clusterArch", "clear"))
        self.clearHMMbtn.setText(_translate("clusterArch", "clear"))
        self.addGeneBtn.setText(_translate("clusterArch", "add"))
        self.addHMMfilePathBtn.setText(_translate("clusterArch", "HMM File Path"))
        self.addGenefilePathBtn.setText(_translate("clusterArch", "Gene File Path"))
        item = self.searchList.horizontalHeaderItem(0)
        item.setText(_translate("clusterArch", "Gene or HMM"))
        item = self.searchList.horizontalHeaderItem(1)
        item.setText(_translate("clusterArch", "Name"))
        self.menuFile.setTitle(_translate("clusterArch", "File"))
        self.menuClose.setTitle(_translate("clusterArch", "Close"))
        self.actionSet_Database.setText(_translate("clusterArch", "Set Database"))
        self.actionOpen_Gene_File.setText(_translate("clusterArch", "Open Gene File"))
        self.actionOpen_HMM_File.setText(_translate("clusterArch", "Open HMM File"))

