# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_parametersWin(object):
    def setupUi(self, parametersWin):
        parametersWin.setObjectName("parametersWin")
        parametersWin.resize(370, 459)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(parametersWin.sizePolicy().hasHeightForWidth())
        parametersWin.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(parametersWin)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parametersWin)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_5 = QtWidgets.QFrame(parametersWin)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parametersWin)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_6 = QtWidgets.QFrame(parametersWin)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.blastEval = QtWidgets.QLineEdit(parametersWin)
        self.blastEval.setText("")
        self.blastEval.setObjectName("blastEval")
        self.horizontalLayout_2.addWidget(self.blastEval)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_4 = QtWidgets.QFrame(parametersWin)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_3 = QtWidgets.QLabel(parametersWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(parametersWin)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parametersWin)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.line_10 = QtWidgets.QFrame(parametersWin)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_3.addWidget(self.line_10)
        self.hmmEval = QtWidgets.QLineEdit(parametersWin)
        self.hmmEval.setText("")
        self.hmmEval.setObjectName("hmmEval")
        self.horizontalLayout_3.addWidget(self.hmmEval)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parametersWin)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.line_9 = QtWidgets.QFrame(parametersWin)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_4.addWidget(self.line_9)
        self.hmmScore = QtWidgets.QLineEdit(parametersWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmmScore.sizePolicy().hasHeightForWidth())
        self.hmmScore.setSizePolicy(sizePolicy)
        self.hmmScore.setText("")
        self.hmmScore.setObjectName("hmmScore")
        self.horizontalLayout_4.addWidget(self.hmmScore)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parametersWin)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.line_8 = QtWidgets.QFrame(parametersWin)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_5.addWidget(self.line_8)
        self.hmmDomLen = QtWidgets.QLineEdit(parametersWin)
        self.hmmDomLen.setText("")
        self.hmmDomLen.setObjectName("hmmDomLen")
        self.horizontalLayout_5.addWidget(self.hmmDomLen)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_2 = QtWidgets.QFrame(parametersWin)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(parametersWin)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.line = QtWidgets.QFrame(parametersWin)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parametersWin)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.line_7 = QtWidgets.QFrame(parametersWin)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_6.addWidget(self.line_7)
        self.windowSize = QtWidgets.QLineEdit(parametersWin)
        self.windowSize.setAcceptDrops(False)
        self.windowSize.setWhatsThis("")
        self.windowSize.setText("")
        self.windowSize.setObjectName("windowSize")
        self.horizontalLayout_6.addWidget(self.windowSize)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.applyBtn = QtWidgets.QPushButton(parametersWin)
        self.applyBtn.setEnabled(False)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout_8.addWidget(self.applyBtn)
        self.closeBtn = QtWidgets.QPushButton(parametersWin)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_8.addWidget(self.closeBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(parametersWin)
        self.closeBtn.clicked.connect(parametersWin.close)
        QtCore.QMetaObject.connectSlotsByName(parametersWin)

    def retranslateUi(self, parametersWin):
        _translate = QtCore.QCoreApplication.translate
        parametersWin.setWindowTitle(_translate("parametersWin", "Search Parameters"))
        self.label.setText(_translate("parametersWin", "BLASTp Settings"))
        self.label_2.setText(_translate("parametersWin", "E-Value Cutoff"))
        self.blastEval.setToolTip(_translate("parametersWin", "Maximum E-value for a BLASTp hit to be considered"))
        self.label_3.setText(_translate("parametersWin", "HMMsearch Settings"))
        self.label_4.setText(_translate("parametersWin", "E-Value Cutoff"))
        self.hmmEval.setToolTip(_translate("parametersWin", "Maximum E-value for a HMMsearch hit to be considered"))
        self.label_5.setText(_translate("parametersWin", "Score Cutoff"))
        self.hmmScore.setToolTip(_translate("parametersWin", "Minimum score for a HMMsearch hit to be considered"))
        self.label_6.setText(_translate("parametersWin", "Minimum Domain Length"))
        self.hmmDomLen.setToolTip(_translate("parametersWin", "Minimum length of HMM hit for it to be considered"))
        self.label_7.setText(_translate("parametersWin", "Archictecture Search Settings"))
        self.label_8.setText(_translate("parametersWin", "Cluster Window Size"))
        self.windowSize.setToolTip(_translate("parametersWin", "Defines maximum nucleotide distance between genes in cluster"))
        self.applyBtn.setText(_translate("parametersWin", "Apply"))
        self.closeBtn.setText(_translate("parametersWin", "Close"))

